FROM "python:3.8-bullseye"
    MAINTAINER Cass <cass@petrus.me>
RUN python -m pip install --no-cache-dir \
    requests \
    streamlit \
    pandas

RUN mkdir /app
WORKDIR /app
COPY scripts/dashboard.py /app
CMD ["python", "-m", "streamlit", "run", "dashboard.py"]
